version: '3.8'

services:
  api:
    build: .
    environment:
      FIBER_HOST: 0.0.0.0
      FIBER_DBHOST: mysql
    ports:
      - 8080:4000
  mysql:
    image: mysql:8.0.22
    volumes:
      - mysql_data:/var/lib/mysql
      - ./sql:/docker-entrypoint-initdb.d
    environment:
      MYSQL_DATABASE: test
      MYSQL_USER: test
      MYSQL_PASSWORD: test
      MYSQL_ROOT_PASSWORD: test

volumes:
  mysql_data:
